name: Deploy AWS Lambda (Node.js & TypeScript)

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Lambda to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Prepare files
        run: |
          mkdir -p package/build
          mkdir -p package/static
          cp lambda/index.js package/index.js
          cp -r node_modules package/node_modules
          cp -r static/* package/static
          cp -r build/* package/build

      - name: Package Lambda
        run: |
          cd package
          zip -r ../lambda.zip *

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          role-session-name: gha-deploy-${{ github.run_id }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://lambda.zip
